Repository gamemanual0/gm0, pull requests merged in 2021-06, with the labels that each got.

#182 Additions to Drawer Slides page
  source/docs/robot-design/linear-motion-guide/drawer-slides.rst
  source/docs/robot-design/linear-motion-guide/images/drawer-slides/misumi-slides-inserts.png
Labels: Hardware, Type: Enhancement

#184 spelling/grammar fixes
  source/docs/awards/award-types.rst
  source/docs/awards/notebook.rst
  source/docs/getting-started-in-ftc/engineering-design-process.rst
  source/docs/getting-started-in-ftc/rookie-building.rst
  source/docs/getting-started-in-ftc/rookie-competition.rst
  source/docs/hardware-basics/kit-and-hardware-guide/3d-printing.rst
  source/docs/hardware-basics/kit-and-hardware-guide/index.rst
  source/docs/hardware-basics/materials-guide.rst
  source/docs/hardware-basics/motor-guide/choosing-motor.rst
  source/docs/hardware-basics/motor-guide/jvn-calculator.rst
  source/docs/hardware-basics/motor-guide/wiring-mounting-motors.rst
  source/docs/hardware-basics/servo-guide/choosing-servo.rst
Labels: Type: Cleanup

#185 Restructure Useful Resources
  source/docs/appendix/index.rst
  source/docs/appendix/useful-resources.rst
  source/docs/robot-design/cad.rst
  source/docs/useful-resources.rst
  source/index.rst
  source/redirects.txt
Labels: Type: Enhancement

#186 Fix 9656's number in the Notebook Gallery
  source/docs/awards/notebook.rst
Labels: Type: Cleanup
