Repository gamemanual0/gm0, pull requests merged in 2021-08, with the labels that each got.

#191 Update/reformat robot gallery
  source/docs/appendix/gallery.rst
Labels: Hardware, Type: Cleanup

#193 Revamp Mecanum Wheel Miniguide
  source/docs/robot-design/drivetrains/holonomic.rst
Labels: Type: Cleanup, Software

#194 Simplify mecanum power normalization
  source/docs/software/mecanum-drive.rst
Labels: Software, Type: Enhancement
