Repository gamemanual0/gm0, pull requests merged in 2021-02, with the labels that each got.

#133 Mecanum Drive Tutorial Improvements
  source/docs/software/mecanum-drive.rst
Labels: Software, Type: Enhancement

#130 Move how to add ADB to PATH
  README.md
  source/docs/software/images/using-android-studio/download-zip.png
  source/docs/software/using-android-studio.rst
Labels: Software, Type: Enhancement

#152 Fix grammar error in Finite State Machines section
  source/docs/software/finite-state-machines.rst
Labels: Type: Spelling/Grammar

#153 Purge contact information of nonmanaging editors
  source/docs/meta/contributors.rst
Labels: Type: Cleanup

#155 Quick spelling fix
  source/docs/power-and-electronics/sensor-glossary.rst
Labels: Type: Spelling/Grammar

#156 Delete count-statistics.sh
  count-statistics.sh
Labels: Type: Cleanup
