Repository gamemanual0/gm0, pull requests merged in 2022-09, with the labels that each got.

#283 Update Rigging
  source/docs/common-mechanisms/linear-motion-guide/images/rigging/cascade-extension.png
  source/docs/common-mechanisms/linear-motion-guide/images/rigging/cascade-retraction.png
  source/docs/common-mechanisms/linear-motion-guide/images/rigging/cascading-retraction.png
  source/docs/common-mechanisms/linear-motion-guide/images/rigging/continuous-extension.png
  source/docs/common-mechanisms/linear-motion-guide/images/rigging/continuous-retraction.jpg
  source/docs/common-mechanisms/linear-motion-guide/images/rigging/continuous-retraction.png
  source/docs/common-mechanisms/linear-motion-guide/images/rigging/continuous-rigging-diagram.jpg
  source/docs/common-mechanisms/linear-motion-guide/rigging.rst
Labels: Hardware, Type: Enhancement

#280 Update Awards
  source/conf.py
  source/docs/awards/award-types.rst
  source/docs/awards/index.rst
  source/docs/awards/judging-presentation.rst
  source/docs/awards/notebook.rst
  source/docs/awards/portfolio.rst
  source/index.rst
Labels: Type: New Page

#287 Align league terms with current FTC definitions.
  source/docs/common-mechanisms/active-intake/principles-of-an-intake.rst
  source/docs/know-your-lingo.rst
Labels: Type: Cleanup

#288 Fix typo in Vendor List
  source/docs/appendix/vendor-list.rst
Labels: Type: Cleanup

#289 Remove broken link from Rigging page
  source/docs/common-mechanisms/linear-motion-guide/rigging.rst
Labels: Type: Cleanup

#291 Fix typo in Linkages page
  source/docs/common-mechanisms/arms/linkages.rst
Labels: Type: Spelling/Grammar, Hardware

#293 Add FTC Docs to Useful Resources
  source/docs/software/tutorials/vision.rst
  source/docs/useful-resources.rst
Labels: Type: Cleanup
