Repository gamemanual0/gm0, pull requests merged in 2022-06, with the labels that each got.

#229 Creation Motion Mounting page for live vs dead vs zombie axle
  source/docs/common-mechanisms/power-transmission/index.rst
  source/docs/common-mechanisms/power-transmission/motion-mounting.rst
Labels: Type: New Page, Hardware

#234 WHAT IS UP GAMERS (issues 163 and 204)
  source/docs/software/control-loops.rst
Labels: Type: New Page, Software

#237 Update 14270 2018-2019 EN/MTI flyer links
  source/docs/appendix/gallery.rst
  source/docs/awards/notebook.rst
Labels: Type: Cleanup

#239 Edit 393 and spm description
  source/docs/power-and-electronics/servo-guide/specialty-servos.rst
Labels: Type: Cleanup, Hardware
