Repository gamemanual0/gm0, pull requests merged in 2022-11, with the labels that each got.

#301 Fix Judge's Manual link
  source/docs/awards/judging-presentation.rst
Labels: Type: Cleanup

#302 Add codespace support
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  pyproject.toml
  source/docs/contributing/contributors.rst
Labels: Type: Structure

#305 Remove most references to VEX/IFI
  source/docs/appendix/vendor-guide.rst
  source/docs/appendix/vendor-list.rst
  source/docs/common-mechanisms/active-intake/types-of-intakes.rst
  source/docs/common-mechanisms/arms/images/linkages/goBILDA-four-bar.png
  source/docs/common-mechanisms/arms/images/linkages/vex-four-bar.png
  source/docs/common-mechanisms/arms/linkages.rst
  source/docs/common-mechanisms/design-tradeoffs.rst
  source/docs/common-mechanisms/drivetrains/holonomic.rst
  source/docs/common-mechanisms/drivetrains/images/holonomic/9829-mecanum.png
  source/docs/contributing/style-guide.rst
  source/docs/hardware-components/kit-and-hardware-guide/gobilda.rst
  source/docs/hardware-components/kit-and-hardware-guide/images/gobilda/thunderhex.png
  source/docs/hardware-components/kit-and-hardware-guide/kit-glossary.rst
  source/docs/power-and-electronics/motor-guide/choosing-motor.rst
  source/docs/power-and-electronics/motor-guide/gearbox-anatomy.rst
  source/docs/power-and-electronics/motor-guide/jvn-calculator.rst
  source/docs/power-and-electronics/motor-guide/motor-current.rst
  source/docs/power-and-electronics/sensor-glossary.rst
  source/docs/power-and-electronics/servo-guide/images/glossary/3736-vex-393-usage.png
  source/docs/power-and-electronics/servo-guide/images/glossary/vex-393.png
  source/docs/power-and-electronics/servo-guide/images/glossary/vex-motor-controller-29.png
  source/docs/power-and-electronics/servo-guide/specialty-servos.rst
  source/docs/power-and-electronics/servo-guide/usage-tips.rst
  source/docs/power-and-electronics/wiring.rst
  source/docs/useful-resources.rst
  source/index.rst
Labels: Type: Cleanup

#306 Modernize software/sensor references
  source/docs/common-mechanisms/dead-wheels.rst
  source/docs/power-and-electronics/sensor-glossary.rst
  source/docs/software/getting-started/options-for-programming.rst
Labels: Type: Cleanup

#311 Fix missing encoder in list in Dead Wheels
  source/docs/common-mechanisms/dead-wheels.rst
Labels: Type: Cleanup

#315 Make feedforward cool
  source/docs/software/concepts/control-loops.rst
Labels: Software, Type: Enhancement

#319 Remove references to VEX Dyno Testing and JVN
  source/docs/common-mechanisms/active-intake/index.rst
  source/docs/common-mechanisms/drivetrains/index.rst
  source/docs/power-and-electronics/motor-guide/choosing-motor.rst
  source/docs/power-and-electronics/motor-guide/images/matrix-curve.png
  source/docs/power-and-electronics/motor-guide/images/motor-power/hd-hex-motor-curve-12V.png
  source/docs/power-and-electronics/motor-guide/images/motor-power/matrix-motor-curve-12V.png
  source/docs/power-and-electronics/motor-guide/images/motor-power/neverest-motor-curve-12V.png
  source/docs/power-and-electronics/motor-guide/images/motor-power/torquenado-motor-curve-12V.png
  source/docs/power-and-electronics/motor-guide/index.rst
  source/docs/power-and-electronics/motor-guide/jvn-calculator.rst
  source/docs/power-and-electronics/motor-guide/motor-power.rst
  source/docs/useful-resources.rst
  source/redirects.txt
Labels: Type: Cleanup

#320 Fixed spelling mistake in the FSM area
  source/docs/software/concepts/finite-state-machines.rst
Labels: Type: Cleanup, Software
