Repository gamemanual0/gm0, pull requests merged in 2022-07, with the labels that each got.

#242 Add Motor current page
  source/docs/power-and-electronics/motor-guide/images/matrix-curve.png
  source/docs/power-and-electronics/motor-guide/index.rst
  source/docs/power-and-electronics/motor-guide/motor-current.rst
Labels: Type: New Page, Hardware

#243 Improve windows build compatibility
  Makefile
  README.md
  make.bat
Labels: Type: Configuration

#211 Add self-retracting cable drawback to rigging page
  source/docs/common-mechanisms/linear-motion-guide/images/cable-management/248-badge-retractor-1.jpg
  source/docs/common-mechanisms/linear-motion-guide/images/cable-management/248-badge-retractor-2.jpg
  source/docs/common-mechanisms/linear-motion-guide/rigging.rst
Labels: Hardware, Type: Enhancement

#214 Minor wording changes
  source/docs/appendix/gallery.rst
  source/docs/know-your-lingo.rst
  source/docs/mission-statement.rst
Labels: Type: Cleanup, Type: Spelling/Grammar

#245 Add gamepad input page
  source/docs/software/gamepad.rst
  source/docs/software/images/gamepad/logitech-f310.png
  source/docs/software/images/gamepad/ps4.png
  source/docs/software/images/gamepad/rising-falling-edge.png
  source/docs/software/images/gamepad/xbox-360.png
  source/docs/software/index.rst
Labels: Type: New Page, Software
