Repository gamemanual0/gm0, pull requests merged in 2022-08, with the labels that each got.

#253 Fix field centric mecanum example code
  source/docs/software/mecanum-drive.rst
Labels: Type: Cleanup, Software

#255 Update information on rankings for Power Play gm1
  source/docs/design-skills/design-strategy.rst
  source/docs/know-your-lingo.rst
Labels: Type: Cleanup

#252 Add common mechanism models
  source/docs/common-mechanisms/arms/linkages.rst
  source/docs/common-mechanisms/drivetrains/holonomic.rst
  source/docs/common-mechanisms/drivetrains/images/holonomic/gobilda-mecanum-direction.png
  source/docs/common-mechanisms/drivetrains/tank.rst
Labels: Hardware, Type: Enhancement

#257 Remove awards section from toctree
  source/index.rst
Labels: Type: Cleanup

#258 Fix build warnings
  source/conf.py
  source/docs/appendix/glossary.rst
  source/docs/common-mechanisms/arms/linkages.rst
  source/docs/know-your-lingo.rst
  source/docs/power-and-electronics/control-system.rst
  source/docs/power-and-electronics/motor-guide/choosing-motor.rst
  source/docs/power-and-electronics/motor-guide/wiring-mounting-motors.rst
  source/docs/power-and-electronics/servo-guide/index.rst
  source/docs/power-and-electronics/servo-guide/specialty-servos.rst
  source/docs/power-and-electronics/servo-guide/usage-tips.rst
  source/docs/power-and-electronics/wiring.rst
  source/docs/software/adv-control-system/control-system-internals.rst
  source/docs/software/adv-control-system/sdk-communication.rst
  source/docs/software/tutorials/bulk-reads.rst
  source/docs/software/tutorials/finite-state-machines.rst
Labels: Type: Cleanup

#262 Fix video URLs in Types of Transfers page
  source/docs/common-mechanisms/transfers/transfer-types.rst
Labels: Type: Cleanup

#264 Refactor Software section
  source/docs/common-mechanisms/arms/index.rst
  source/docs/common-mechanisms/dead-wheels.rst
  source/docs/software/concepts/control-loops.rst
  source/docs/software/concepts/finite-state-machines.rst
  source/docs/software/concepts/images/control-loops/trapezoidal-motion-profiling-graph.png
  source/docs/software/concepts/images/odometry/coordinate-frame.png
  source/docs/software/concepts/images/odometry/offsets-and-trackwidth.png
  source/docs/software/concepts/index.rst
  source/docs/software/concepts/odometry.rst
  source/docs/software/getting-started/fundamental-concepts.rst
  source/docs/software/index.rst
  source/docs/software/tutorials/index.rst
  source/redirects.txt
Labels: Type: Structure, Software

#265 Enable fail_on_warning in readthedocs.yaml
  .readthedocs.yaml
Labels: Type: Configuration

#267 Disable epub build, set the version to 0
  .readthedocs.yaml
  source/conf.py
Labels: Type: Configuration

#263 Add Kinematics Page
  source/docs/software/concepts/index.rst
  source/docs/software/concepts/kinematics.rst
Labels: Type: New Page, Software

#268 Add Karthik's talk in design skills
  source/docs/design-skills/design-strategy.rst
Labels: Type: Enhancement

#271 Fix incorrect directive in Telemetry page
  source/docs/software/tutorials/using-telemetry.rst
Labels: Type: Cleanup, Software

#275 Add 20700 to multi axis arms
  source/docs/common-mechanisms/arms/images/multi-axis-arm/20700-snap.png
  source/docs/common-mechanisms/arms/multi-axis-arm.rst
Labels: Hardware, Type: Enhancement

#277 Add encoder labels to odometry gallery
  source/docs/common-mechanisms/dead-wheels.rst
Labels: Hardware, Type: Enhancement

#278 Improve 3D Printing Filament Guide
  .gitignore
  source/docs/custom-manufacturing/3d-printing.rst
Labels: Hardware, Type: Enhancement

#279 Add empty setup function to conf.py
  source/conf.py
Labels: Type: Configuration

#281 Mention English terms appearing in translations
  source/index.rst
Labels: Type: Enhancement

#282 Change configuration options for translation
  source/conf.py
Labels: Type: Configuration

#284 Fix adb screenshot
  source/docs/software/getting-started/images/using-android-studio/adb-screenshot.png
  source/docs/software/getting-started/using-android-studio.rst
Labels: Type: Cleanup, Software

#285 Add 12518 Freight Frenzy to Robot Gallery
  source/docs/appendix/gallery.rst
Labels: Hardware, Type: Enhancement
