Repository gamemanual0/gm0, pull requests merged in 2023-09, with the labels that each got.

#390 Fix typo in rack and pinion page
  source/docs/common-mechanisms/linear-motion-guide/rack-and-pinion.rst
Labels: Type: Spelling/Grammar, Hardware

#393 Add inline belt calculator
  source/_static/calculator-utils.js
  source/docs/common-mechanisms/power-transmission/belt-calculator.html
  source/docs/common-mechanisms/power-transmission/belt.rst
Labels: Hardware, Type: Enhancement

#396 Remove 17077 2020-2021 CAD from Gallery
  source/docs/appendix/gallery.rst
Labels: Type: Cleanup
