Repository gamemanual0/gm0, pull requests merged in 2023-04, with the labels that each got.

#345 Update software glossary to mention Driver Hub
  .github/workflows/CI.yml
  source/docs/software/software-glossary.rst
Labels: Type: Cleanup, Software

#352 Reorganize Contributor's page
  source/docs/contributing/contributors.rst
Labels: Type: Cleanup

#349 Add a Being a Team section
  source/docs/being-a-team/collaboration-and-efficiency.rst
  source/docs/being-a-team/images/collaboration-and-efficiency/intake_competitive_prototyping.png
  source/docs/being-a-team/index.rst
  source/docs/being-a-team/outreach-basics.rst
  source/docs/being-a-team/pitching-your-team.rst
  source/docs/being-a-team/starting-a-team.rst
  source/docs/being-a-team/team-organization.rst
  source/docs/contributing/contributors.rst
  source/docs/start-here.rst
  source/index.rst
Labels: Type: New Page

#353 Set tabSize to 3 spaces for codespaces
  .devcontainer/devcontainer.json
Labels: Type: Configuration

#354 Added Axon to vendor list
  source/docs/appendix/vendor-guide.rst
  source/docs/appendix/vendor-list.rst
Labels: Hardware, Type: Enhancement
