Repository gamemanual0/gm0, pull requests merged in 2023-10, with the labels that each got.

#397 Remove try block for no longer thrown exception
  source/docs/software/tutorials/gamepad.rst
Labels: Type: Cleanup, Software

#398 Remove Weighted Objectives from Useful Resources
  source/docs/useful-resources.rst
Labels: Type: Cleanup

#391 Add Drivers Hub to Driver Station page
  source/docs/power-and-electronics/driver-station-guide.rst
Labels: Type: Enhancement

#392 Hardware kit page refactoring
  source/docs/hardware-components/kit-and-hardware-guide/actobotics.rst
  source/docs/hardware-components/kit-and-hardware-guide/gobilda.rst
  source/docs/hardware-components/kit-and-hardware-guide/images/gobilda/gobilda_mini_channel.jpg
  source/docs/hardware-components/kit-and-hardware-guide/index.rst
  source/docs/hardware-components/kit-and-hardware-guide/rev-robotics.rst
  source/docs/hardware-components/kit-and-hardware-guide/tetrix.rst
Labels: Type: Enhancement

#395 Updates to choosing servos page
  source/docs/power-and-electronics/servo-guide/choosing-servo.rst
Labels: Hardware

#400 Buying belts
  source/docs/common-mechanisms/power-transmission/belt.rst
Labels: Hardware, Type: Enhancement

#402 Fix linkcheck errors
  source/conf.py
  source/docs/common-mechanisms/dead-wheels.rst
  source/docs/custom-manufacturing/laser-cutting.rst
  source/docs/custom-manufacturing/materials-guide.rst
Labels: Type: Cleanup

#403 Change COREFTC link to FTC Docs 3D Printing Section
  source/docs/custom-manufacturing/3d-printing.rst
Labels: Type: Cleanup

#404 Set default image width/alignment with a sphinx extension
  .gitignore
  source/_extensions/default_image_settings.py
  source/_static/custom.css
  source/conf.py
Labels: Type: Configuration, Type: Style/CSS

#406 Replace unicode chars that RST auto-substitutes
  source/docs/awards/award-types.rst
  source/docs/being-a-team/collaboration-and-efficiency.rst
  source/docs/being-a-team/outreach-basics.rst
  source/docs/being-a-team/pitching-your-team.rst
  source/docs/being-a-team/starting-a-team.rst
  source/docs/common-mechanisms/active-intake/index.rst
  source/docs/common-mechanisms/active-intake/principles-of-an-intake.rst
  source/docs/common-mechanisms/active-intake/types-of-intakes.rst
  source/docs/common-mechanisms/arms.rst
  source/docs/common-mechanisms/design-tradeoffs.rst
  source/docs/common-mechanisms/drivetrains/holonomic.rst
  source/docs/common-mechanisms/drivetrains/index.rst
  source/docs/common-mechanisms/drivetrains/tank.rst
  source/docs/common-mechanisms/linear-motion-guide/custom.rst
  source/docs/common-mechanisms/linear-motion-guide/drawer-slides.rst
  source/docs/common-mechanisms/linear-motion-guide/extrusion-slides.rst
  source/docs/common-mechanisms/linear-motion-guide/index.rst
  source/docs/common-mechanisms/linear-motion-guide/rigging.rst
  source/docs/common-mechanisms/passive-intake-claw.rst
  source/docs/common-mechanisms/power-transmission/belt.rst
  source/docs/common-mechanisms/power-transmission/chain.rst
  source/docs/common-mechanisms/power-transmission/direct-drive.rst
  source/docs/common-mechanisms/power-transmission/gears.rst
  source/docs/common-mechanisms/power-transmission/power-transmission-glossary.rst
  source/docs/contributing/contributors.rst
  source/docs/contributing/index.rst
  source/docs/contributing/style-guide.rst
  source/docs/custom-manufacturing/laser-cutting.rst
  source/docs/custom-manufacturing/materials-guide.rst
  source/docs/design-skills/cad-tutorials.rst
  source/docs/design-skills/cad.rst
  source/docs/design-skills/design-glossary.rst
  source/docs/design-skills/design-strategy.rst
  source/docs/design-skills/engineering-design-process.rst
  source/docs/hardware-components/kit-and-hardware-guide/actobotics.rst
  source/docs/hardware-components/kit-and-hardware-guide/gobilda.rst
  source/docs/hardware-components/kit-and-hardware-guide/index.rst
  source/docs/hardware-components/kit-and-hardware-guide/kit-glossary.rst
  source/docs/hardware-components/kit-and-hardware-guide/rev-robotics.rst
  source/docs/hardware-components/kit-and-hardware-guide/tetrix.rst
  source/docs/hardware-components/tools-list.rst
  source/docs/mission-statement.rst
  source/docs/power-and-electronics/connectors-and-wires.rst
  source/docs/power-and-electronics/control-system.rst
  source/docs/power-and-electronics/motor-guide/choosing-motor.rst
  source/docs/power-and-electronics/motor-guide/gearbox-anatomy.rst
  source/docs/power-and-electronics/motor-guide/motor-glossary.rst
  source/docs/power-and-electronics/sensor-glossary.rst
  source/docs/power-and-electronics/servo-guide/choosing-servo.rst
  source/docs/power-and-electronics/servo-guide/index.rst
  source/docs/power-and-electronics/wiring.rst
  source/docs/software/concepts/control-loops.rst
  source/docs/software/concepts/finite-state-machines.rst
  source/docs/software/getting-started/common-hardware-components.rst
  source/docs/software/getting-started/fundamental-concepts.rst
  source/docs/software/getting-started/options-for-programming.rst
  source/docs/software/tutorials/mecanum-drive.rst
  source/docs/software/tutorials/vision.rst
  source/docs/useful-resources.rst
Labels: Type: Cleanup
