Repository gamemanual0/gm0, pull requests merged in 2023-11, with the labels that each got.

#409 Update control systems
  source/docs/power-and-electronics/control-system.rst
Labels: Software, Type: Enhancement

#410 Split Build Job into Build HTML and Build PDF
  .github/workflows/CI.yml
Labels: Type: Configuration

#412 Install Graphviz in CI HTML Build
  .github/workflows/CI.yml
Labels: Type: Configuration

#413 Tweak Custom CSS
  source/_static/custom.css
Labels: Type: Style/CSS

#414 Fix typo in encoders page
  source/docs/software/tutorials/encoders.rst
Labels: Type: Spelling/Grammar, Software
