Repository gamemanual0/gm0, pull requests merged in 2023-07, with the labels that each got.

#369 Update Mission Statement
  source/docs/mission-statement.rst
Labels: Type: Cleanup

#371 Add Keval to contributors page
  source/docs/contributing/contributors.rst
Labels: Type: Cleanup

#373 Update Github actions versions
  .github/workflows/CI.yml
  .github/workflows/link-check.yml
Labels: Type: Configuration

#376 add images for materials in the materials guide
  source/docs/custom-manufacturing/images/materials-guide/abs-banner.jpg
  source/docs/custom-manufacturing/images/materials-guide/acetal-banner.jpg
  source/docs/custom-manufacturing/images/materials-guide/aluminum-banner.jpg
  source/docs/custom-manufacturing/images/materials-guide/hdpe-banner.jpg
  source/docs/custom-manufacturing/images/materials-guide/polycarbonate-banner.jpg
  source/docs/custom-manufacturing/materials-guide.rst
Labels: Hardware, Type: Enhancement

#378 Fixes #337
  source/docs/software/concepts/finite-state-machines.rst
Labels: Type: Cleanup, Software
