Repository gamemanual0/gm0, pull requests merged in 2023-05, with the labels that each got.

#355 Fix links for embedded linkage CAD models
  source/docs/common-mechanisms/linkages.rst
Labels: Type: Cleanup, Hardware

#357 Team Management Changes
  source/docs/being-a-team/outreach-basics.rst
Labels: Type: Cleanup

#358 Add autodesk.com to linkcheck_ignore
  source/conf.py
Labels: Type: Configuration

#300 Encoders 101
  source/docs/software/tutorials/block-code/arm-opmode.blk
  source/docs/software/tutorials/block-code/encoder-opmode.blk
  source/docs/software/tutorials/block-code/mecanum-drive-sample.blk
  source/docs/software/tutorials/block-code/spool-encoder-opmode.blk
  source/docs/software/tutorials/encoders.rst
  source/docs/software/tutorials/images/encoders/arm-opmode-1.png
  source/docs/software/tutorials/images/encoders/arm-opmode-2.png
  source/docs/software/tutorials/images/encoders/arm-opmode-3.png
  source/docs/software/tutorials/images/encoders/arm-opmode-complete.png
  source/docs/software/tutorials/images/encoders/encoder-opmode-1.png
  source/docs/software/tutorials/images/encoders/encoder-opmode-2.png
  source/docs/software/tutorials/images/encoders/encoder-opmode-3.png
  source/docs/software/tutorials/images/encoders/encoder-opmode-4.png
  source/docs/software/tutorials/images/encoders/encoder-opmode-5.png
  source/docs/software/tutorials/images/encoders/encoder-opmode-complete.png
  source/docs/software/tutorials/images/encoders/spool-encoder-opmode-1.png
  source/docs/software/tutorials/images/encoders/spool-encoder-opmode-complete.png
  source/docs/software/tutorials/index.rst
  source/docs/software/tutorials/mecanum-drive.rst
Labels: Type: New Page, Software

#360 Move warning about VEX/IFI's culture
  source/docs/hardware-components/kit-and-hardware-guide/index.rst
  source/index.rst
Labels: Type: Cleanup
