Repository gamemanual0/gm0, pull requests merged in 2024-03, with the labels that each got.

#427 Add Shaft Retention Page
  source/docs/common-mechanisms/power-transmission/images/shaft-retention/clamping-shaft-collar.png
  source/docs/common-mechanisms/power-transmission/images/shaft-retention/set-screw-shaft-collar.png
  source/docs/common-mechanisms/power-transmission/images/shaft-retention/shaft-with-eclip.jpg
  source/docs/common-mechanisms/power-transmission/index.rst
  source/docs/common-mechanisms/power-transmission/motion-mounting.rst
  source/docs/common-mechanisms/power-transmission/shaft-retention.rst
Labels: Type: New Page, Hardware

#428 Update choosing-servo.rst
  source/docs/power-and-electronics/servo-guide/choosing-servo.rst
Labels: Type: Spelling/Grammar

#429 Update vendor-list.rst
  source/docs/appendix/vendor-list.rst
Labels: Hardware, Type: Enhancement
